In [1]:
%load_ext autoreload 
%autoreload 2

In [2]:
import sys

In [8]:
sys.path

['/Users/sidravi/Documents/IDInsight/IndusAction/ia_power/playground/Sid',
 '/Users/sidravi/anaconda3/envs/indus_action/lib/python38.zip',
 '/Users/sidravi/anaconda3/envs/indus_action/lib/python3.8',
 '/Users/sidravi/anaconda3/envs/indus_action/lib/python3.8/lib-dynload',
 '',
 '/Users/sidravi/anaconda3/envs/indus_action/lib/python3.8/site-packages',
 '/Users/sidravi/anaconda3/envs/indus_action/lib/python3.8/site-packages/IPython/extensions',
 '/Users/sidravi/.ipython']

In [5]:
%config Completer.use_jedi = False

In [6]:
import os


In [7]:
os.chdir("../..")

In [9]:
import numpy as np
import pandas as pd

In [10]:
import src.nodes.calculation as cl

In [11]:
import src.nodes.benefits as bft
import src.nodes.beneficiary as clm
import src.nodes.calculation as cal
import src.nodes.checkers as chk
from pathlib import Path

In [12]:
benefits_x_criteria = bft.load_sample_benefits_matrix("sample_benefits_2")
beneficiary_x_criteria = clm.load_sample_beneficiary_matrix("sample_beneficiary_2")

In [13]:
chk.check_matrix_sanity(benefits_x_criteria, beneficiary_x_criteria)

True

In [9]:
benefits_x_criteria

criteria1  criteria2  criteria3  criteria4  criteria5
benefit_name                                                       
ABC                   1          1          1          1          0
XYZ                   0          0          1          1          1

In [10]:
beneficiary_x_criteria

criteria1  criteria2  criteria3  criteria4  criteria5
beneficiary_name                                                       
Sid                     1.0        NaN          1          0        0.0
Tanmay                  1.0        0.0          1          1        1.0
Victor                  1.0        1.0          1          1        NaN
Shreya                  NaN        1.0          1          1        1.0

In [16]:
cal.get_clamped_score(pd.DataFrame([[1, 0]]), pd.DataFrame([[np.nan, 1]]))

0
0  0.0

In [12]:
X = np.array(benefits_x_criteria)
Y = np.array(beneficiary_x_criteria)

Y_nan_mask = Y

In [35]:
X[0]

array([1, 1, 1, 1, 0])

In [36]:
Y[0]

array([ 1., nan,  1.,  0.,  0.])

In [55]:
is_nan = np.isnan(Y[0])
rules = np.logical_not(np.logical_xor(X[0][~is_nan], Y[0][~is_nan])).all()
rules

False

In [61]:
score = 1 - (np.isnan(Y[0]) & X[0]).sum() / np.sum(X[0])
score

0.75

In [63]:
X

array([[1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1]])

In [64]:
Y

array([[ 1., nan,  1.,  0.,  0.],
       [ 1.,  0.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1.]])

In [86]:
from itertools import product

In [107]:
np.where(x[~is_nan], y[~is_nan], 1)

array([1., 1., 0., 1.])

In [108]:
x

array([1, 1, 1, 1, 0])

In [109]:
y

array([ 1., nan,  1.,  0.,  0.])

In [110]:
~is_nan

array([ True, False,  True,  True,  True])

In [114]:
outcome = np.zeros((len(Y), len(X)))
for (i, j) in product(range(len(Y)), range(len(X))):

    y = Y[i]
    x = X[j]
    
    is_nan = np.isnan(y)
    rules = np.where(x[~is_nan], y[~is_nan], 1)
    if rules.all():
        score = 1 - (np.isnan(y) & x).sum() / np.sum(x)
    else:
        score = 0
    outcome[i, j] = score


[1 1 1 1 0] [ 1. nan  1.  0.  0.]
[1. 1. 0. 1.]
0
-------
[0 0 1 1 1] [ 1. nan  1.  0.  0.]
[1. 1. 0. 0.]
0
-------
[1 1 1 1 0] [1. 0. 1. 1. 1.]
[1. 0. 1. 1. 1.]
0
-------
[0 0 1 1 1] [1. 0. 1. 1. 1.]
[1. 1. 1. 1. 1.]
1.0
-------
[1 1 1 1 0] [ 1.  1.  1.  1. nan]
[1. 1. 1. 1.]
1.0
-------
[0 0 1 1 1] [ 1.  1.  1.  1. nan]
[1. 1. 1. 1.]
0.6666666666666667
-------
[1 1 1 1 0] [nan  1.  1.  1.  1.]
[1. 1. 1. 1.]
0.75
-------
[0 0 1 1 1] [nan  1.  1.  1.  1.]
[1. 1. 1. 1.]
1.0
-------


In [79]:
for x,y in zip(np.meshgrid(X, Y)):
    print(x)
    print("-----")

ValueError: not enough values to unpack (expected 2, got 1)